### ISSUE TITLE
Configure project :screen WARNING: The specified Android SDK Build Tools version (25.0.3) .....

### ISSUE THREAD

**Issue by msterzhang** [clovisnicolas/flutter_screen#11]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "E:\java\Android\Course\youtube\android\gradlew.bat" exited abnormally:

> Configure project :screen
WARNING: The specified Android SDK Build Tools version (25.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Checking the license for package Android SDK Platform 25 in D:\Android_sdk\licenses
Warning: License for package Android SDK Platform 25 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':screen'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     platforms;android-25 Android SDK Platform 25
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html

  Using Android SDK: D:\Android_sdk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
  Command: E:\java\Android\Course\youtube\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by hillelcoren** [comment]
I was able to fix this by running: flutter doctor --android-licenses

**Comment by msterzhang** [comment]
thank you very much! It is very effective!
